# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `rails
# db:schema:load`. When creating a new database, `rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[6.1].define(version: 2020_05_13_013701) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "allstars", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.string "game_id"
    t.string "team_id"
    t.string "lg_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "fielding_stats", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.integer "stint"
    t.string "team_id"
    t.string "lg_id"
    t.string "pos"
    t.integer "g"
    t.integer "gs"
    t.integer "inn_outs"
    t.integer "po"
    t.integer "a"
    t.integer "e"
    t.integer "dp"
    t.integer "pb"
    t.integer "wp"
    t.integer "sb"
    t.integer "cs"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "franchises", force: :cascade do |t|
    t.string "franch_id"
    t.string "franch_name"
    t.string "active"
    t.string "na_assoc"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "games_nineteen_tens", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "hall_of_fames", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.string "inducted"
    t.string "category"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "hitting_stats", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.integer "stint"
    t.string "team_id"
    t.string "lg_id"
    t.integer "g"
    t.integer "ab"
    t.integer "r"
    t.integer "h"
    t.integer "doubles"
    t.integer "triples"
    t.integer "hr"
    t.integer "rbi"
    t.integer "sb"
    t.integer "cs"
    t.integer "bb"
    t.integer "so"
    t.integer "ibb"
    t.integer "hbp"
    t.integer "sh"
    t.integer "sf"
    t.integer "gidp"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "pitching_stats", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.integer "stint"
    t.string "team_id"
    t.string "lg_id"
    t.integer "w"
    t.integer "l"
    t.integer "g"
    t.integer "gs"
    t.integer "cg"
    t.integer "sho"
    t.integer "sv"
    t.integer "ip_outs"
    t.integer "h"
    t.integer "er"
    t.integer "hr"
    t.integer "bb"
    t.integer "so"
    t.decimal "ba_opp", precision: 4, scale: 3
    t.decimal "era", precision: 5, scale: 2
    t.integer "ibb"
    t.integer "wp"
    t.integer "hbp"
    t.integer "bk"
    t.integer "bfp"
    t.integer "gf"
    t.integer "r"
    t.integer "sh"
    t.integer "sf"
    t.integer "gidp"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_eighties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_fifties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_forties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_nineties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_seventies", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_sixties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_thirties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_nineteen_twenties", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_two_thousand_tens", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "play_by_play_two_thousands", force: :cascade do |t|
    t.string "game_id"
    t.string "away_team_id"
    t.integer "inn_ct"
    t.integer "bat_home_id"
    t.integer "outs_ct"
    t.integer "balls_ct"
    t.integer "strikes_ct"
    t.integer "away_score_ct"
    t.integer "home_score_ct"
    t.string "resp_bat_id"
    t.string "resp_bat_hand_cd"
    t.string "resp_pit_id"
    t.string "resp_pit_hand_cd"
    t.string "base1_run_id"
    t.string "base2_run_id"
    t.string "base3_run_id"
    t.string "event_tx"
    t.string "leadoff_fl"
    t.string "ph_fl"
    t.integer "bat_fld_cd"
    t.integer "bat_lineup_id"
    t.integer "event_cd"
    t.string "bat_event_fl"
    t.string "ab_fl"
    t.integer "h_fl"
    t.string "sh_fl"
    t.string "sf_fl"
    t.integer "event_outs_ct"
    t.integer "rbi_ct"
    t.string "wp_fl"
    t.string "pb_fl"
    t.integer "err_ct"
    t.string "bat_dest_id"
    t.string "run1_dest_id"
    t.string "run2_dest_id"
    t.string "run3_dest_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "player_awards", force: :cascade do |t|
    t.string "player_id"
    t.string "award_id"
    t.integer "year_id"
    t.string "lg_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "players", force: :cascade do |t|
    t.string "player_id"
    t.integer "birth_year"
    t.integer "birth_month"
    t.integer "birth_day"
    t.string "birth_country"
    t.string "birth_state"
    t.string "birth_city"
    t.integer "death_year"
    t.integer "death_month"
    t.integer "death_day"
    t.string "death_country"
    t.string "death_state"
    t.string "death_city"
    t.string "first_name"
    t.string "last_name"
    t.string "given_name"
    t.integer "weight"
    t.integer "height"
    t.string "bats"
    t.string "throws"
    t.date "debut"
    t.date "final_game"
    t.string "retro_id"
    t.string "bbref_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "post_fielding_stats", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.string "team_id"
    t.string "lg_id"
    t.string "round"
    t.string "pos"
    t.integer "g"
    t.integer "gs"
    t.integer "inn_outs"
    t.integer "po"
    t.integer "a"
    t.integer "e"
    t.integer "dp"
    t.integer "tp"
    t.integer "pb"
    t.integer "sb"
    t.integer "cs"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "post_hitting_stats", force: :cascade do |t|
    t.integer "year_id"
    t.string "round"
    t.string "player_id"
    t.string "team_id"
    t.string "lg_id"
    t.integer "g"
    t.integer "ab"
    t.integer "r"
    t.integer "h"
    t.integer "doubles"
    t.integer "triples"
    t.integer "hr"
    t.integer "rbi"
    t.integer "sb"
    t.integer "cs"
    t.integer "bb"
    t.integer "so"
    t.integer "ibb"
    t.integer "hbp"
    t.integer "sh"
    t.integer "sf"
    t.integer "gidp"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "post_pitching_stats", force: :cascade do |t|
    t.string "player_id"
    t.integer "year_id"
    t.string "round"
    t.string "team_id"
    t.string "lg_id"
    t.integer "w"
    t.integer "l"
    t.integer "g"
    t.integer "gs"
    t.integer "cg"
    t.integer "sho"
    t.integer "sv"
    t.integer "ip_outs"
    t.integer "h"
    t.integer "er"
    t.integer "hr"
    t.integer "bb"
    t.integer "so"
    t.decimal "ba_opp", precision: 4, scale: 3
    t.string "era"
    t.integer "ibb"
    t.integer "wp"
    t.integer "hbp"
    t.integer "bk"
    t.integer "bfp"
    t.integer "gf"
    t.integer "r"
    t.integer "sh"
    t.integer "sf"
    t.integer "gidp"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "salaries", force: :cascade do |t|
    t.string "year_id"
    t.string "team_id"
    t.string "lg_id"
    t.string "player_id"
    t.integer "salary"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "team_stats", force: :cascade do |t|
    t.integer "year_id"
    t.string "lg_id"
    t.string "team_id"
    t.string "franch_id"
    t.string "div_id"
    t.integer "rank"
    t.integer "g"
    t.integer "g_home"
    t.integer "w"
    t.integer "l"
    t.string "div_win"
    t.string "wc_win"
    t.string "lg_win"
    t.string "ws_win"
    t.integer "r"
    t.integer "ab"
    t.integer "h"
    t.integer "doubles"
    t.integer "triples"
    t.integer "hr"
    t.integer "bb"
    t.integer "so"
    t.integer "sb"
    t.integer "cs"
    t.integer "hbp"
    t.integer "sf"
    t.integer "ra"
    t.integer "er"
    t.decimal "era", precision: 3, scale: 2
    t.integer "cg"
    t.integer "sho"
    t.integer "sv"
    t.integer "ip_outs"
    t.integer "ha"
    t.integer "bba"
    t.integer "soa"
    t.integer "e"
    t.integer "dp"
    t.decimal "fp", precision: 4, scale: 3
    t.string "name"
    t.string "park"
    t.integer "attendance"
    t.integer "bpf"
    t.integer "ppf"
    t.string "team_id_br"
    t.string "team_id_lahman"
    t.string "team_id_retro"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "hra"
  end

end
